#  status
GET http://localhost:8080/status
Content-Type: application/json

{ }

### 
# products
GET http://localhost:8080/products
Content-Type: application/json

{ }

### 
# feedback
POST http://localhost:8080/products/cars-vr/feedback
Content-Type: application/json

{
}
