#  status
GET http://localhost:8080/status
Content-Type: application/json

{ }

### 
# products
GET http://localhost:8080/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im1VYzJ5UVlqMkRDTmk2V2t3X2F4QSJ9.eyJpc3MiOiJodHRwczovL2Rldi1ocjFwenhucS51cy5hdXRoMC5jb20vIiwic3ViIjoiQ29mYThvcXFhY3NBMTZSZXZrUVVsWXZiaUJQckRQOGVAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vYXV0aDAuY29tL2Jsb2cvYXV0aGVudGljYXRpb24taW4tZ29sYW5nLyIsImlhdCI6MTU5NjM0NTc3MCwiZXhwIjoxNTk2NDMyMTcwLCJhenAiOiJDb2ZhOG9xcWFjc0ExNlJldmtRVWxZdmJpQlByRFA4ZSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.dzNnBYC8aoWhnf9kyUvL9PJa2Rx2PhoLp_L59lyxA_DMebuO3Z00syZL11yGvP_j7scchCs65ZRzOHQ9Z8EzAw9O7AGdvIvG3L4SKz2Dv97HK_bFXqyGIUGBo1nQxiO4KrYYFp-OtA6ee3KrqiNYA9prwALF_3mqqDRGmMxbbHpjvt4NbulIiy_2dpejQtuQTjR3UCiZZR_m91pjktoYcvLn1T0aNyv66bTKl2sJpPPctWeKVfq17gcFQ1tf32xo18XEHXSUvQXSBh-MUvyZZQX0hIc3PhZKodKHHOvo5GpOmCLClwp6eEQ-8ejDwGd6ICF8zATLX1phxYsdAct6Ew

{ }

### 
# feedback
POST http://localhost:8080/products/cars-vr/feedback
Content-Type: application/json

{ }
